# Generated by Django 6.1 on 2026-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=5)),
                ('unit', models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kilogram'), ('lt', 'Litre'), ('paket', 'Paket')], default='adet', max_length=10)),
            ],
        ),
    ]
