# Generated by Django 6.1 on 2026-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Adet', max_length=20),
        ),
    ]
