# Generated by Django 6.1 on 2026-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HAMMADDE', 'Hammadde'), ('YARI_MAMUL', 'Yarı Mamul'), ('MAMUL', 'Mamul'), ('DIGER', 'Diğer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ADET', 'Adet'), ('LEVHA', 'Levha'), ('METRE', 'Metre'), ('KG', 'Kilogram'), ('PAKET', 'Paket')], max_length=20),
        ),
    ]
